
#search
salesman_item=RoadReadyWheel_TestSKU
item=Mercury Villager Steel Wheel / Rim
ponumber=123
cardNumber=411111111111111
SecurityCode=121
AfterLOginText=Shop Road Ready Products
wholesaleitem=RoadReadyWheel_TestSKU
Paypalitem=Ford
paypaluserpassword=3lAq23<!
switch_to_resale_msg=Click on the button below to checkout with 'resale' pricing
ResalePrice_validation=$150.00
Ground_shipping_price=Free
Overnight_shipping_Text=Overnight Shipping
userEmail=ruby.sharma@w3villa.com
G-payemail=ruby.sharma@w3villa.com
G-payemail_password=Ruby@1985
Gpay_shipping_Text=$0.00: Ground Shipping (FREE)

#---------------------------------guest user------------------
Email_Id=Ruby.Sharma@w3villa.com
First_Name=ruby
Last_Name=sharma
Address_Line_1=Kern
Address_Line_2=action
City_Name=LosAngeles
Zip_Code=90001
Mobile_Number=111111111111
Company=w3villa

-----------------payment------------------
customername=rishabh
cvv=921
Expiry_Date=09/2027