# Enable Spark HTML reporter
extent.reporter.spark.start=true
extent.reporter.spark.out=target/ExtentReports/SparkReport.html
extent.reporter.spark.append=false

extent.reporter.spark.config=src/test/resources/spark-config.xml

# Optional PDF reporter
extent.reporter.pdf.start=false
extent.reporter.pdf.out=target/ExtentReports/ExtentReport.pdf

# System info
systeminfo.user=AUTOMATION TESTING ENGINEER
systeminfo.project=RoadReadyWheels API Automation
systeminfo.environment=Staging
systeminfo.os=${os.name}

# Show skipped tests
extent.skipped.tests=true