
#search
salesman_item=RoadReadyWheel_TestSKU
item=Mercury Villager Steel Wheel / Rim
ponumber=123
cardNumber=411111111111111
SecurityCode=121
AfterLOginText=Shop Road Ready Products
wholesaleitem=RoadReadyWheel_TestSKU
Paypalitem=Ford
paypaluserpassword=3lAq23<!
switch_to_resale_msg=Click on the button below to checkout with 'resale' pricing
ResalePrice_validation=$150.00
Ground_shipping_price=Free
Overnight_shipping_Text=Overnight Shipping
userEmail=ruby.sharma@w3villa.com
G-payemail=ruby.sharma@w3villa.com
G-payemail_password=Ruby@1985
Gpay_shipping_Text=$0.00: Ground Shipping (FREE)
# Search Item 1 Details staging
AfterFilterResultText=Showing products that are compatible with Aluminum, 16\u2033, 5-105mm or 5-4.13
FilterProductResultText=
Searchitemkey1=Ford Transit Rim 16x6.5
Searchitemkey1_TextResult=Showing products that are compatible with Ford Transit Rim 16x6.5
Searchitem1TextKeyword1_xpath_LinkText=2010-2013 15x6 Ford Transit Steel Wheel / Rim
# Search Item 2 Details staging
ItemKey2=Toyota Chrome 5 4-108mm or 4-4.25 19" 2012
ItemKey2Text= Showing products that are compatible with Toyota Chrome 5 4-108mm or 4-4.25 19" 2012
ItemKey2_xpath_LinkText=2010-2017 17x7 Toyota 4Runner Steel Wheel / Rim
# Search Item 3 Details staging
ItemKey3=2004-2012 17x7 ,BMW , Steel Wheel / Rim,530i,10,5-100mm
ItemKey3Text=Showing products that are compatible with 2004-2012 17x7 ,BMW , Steel Wheel / Rim,530i,10,5-100mm
ItemKey3_xpath_LinkText=2004-2007 17x7.5 BMW 530i Aluminum Wheel / Rim
#--------------------------------------- Search Item 4 Details staging---------------------------------------------
ItemKey4=maruti i10
ItemKey4Text=Sorry, we couldn't find any matches for "maruti i10" With Filters
ItemKey4_xpath_LinkText=Retry search without filters
After_Reset_Button=Shop Road Ready Products
#----------------------------------------------------------------AddtoCart Functionality Data------------------------------------
item_1=2007-2011 16x6.5 Toyota Camry Steel Wheel /Rim
item_XpathText_1=2007-2011 16x6.5 Toyota Camry Steel Wheel /Rim
Total_Price1=$78.39
#---------------------------------guest user------------------
Email_Id=Ruby.Sharma@w3villa.com
First_Name=ruby
Last_Name=sharma
Address_Line_1=Kern
Address_Line_2=action
City_Name=LosAngeles
Zip_Code=90001
Mobile_Number=111111111111
Company=w3villa
#----------salesman view------------------f
DashboardAfter_clickonSalesmanView=Road Ready Idea Hub
EnableMessage_forSalesmanView=Salesmen view enabled.
Salesmanview_CartItem_Details=SSKU: 560-1001
multiprice_option_Message=["You can't Switch to multi price option with incomplete order."]
multiprice_cart_price=$150.0
Your_cost=$150.0Your Cost
Pallet_cost=$90.00Pallet Cost
-----------------payment------------------
customername=rishabh
cvv=921
Expiry_Date=09/2027