ValidPssword=123456
InvalidEmail_pasword=Invalid Email or password.
Invalid_Pssword1=64$7gydb1
Forget_email=ruby.sharma@w3villa.com
Email_not_found_message=Email not found
login_success_message = Successfully logged in
login_unsuccess_message = Invalid email or password
#---------------------Create account form-----------------------
Enter_userEmail=rubyruby@gmail.com
CompanyName=w3villa.com
Password=ghhbh878
Confirm_Password=-----@2
Account_not_created_message=There were problems with the following fields:
invalidZip_code=677500
Valid_zipcode=30012
zipcode_error_message=We use Google to get info about your zipcode. 
#------------------validation-----------------------------
listing_page_url_afterlogin = "https://staging.roadreadywheels.com/t/categories";
#-----------------------assertion_listing_page---------------------------------
url_lisitng_page=https://staging.roadreadywheels.com/t/categories
heading_listing_page=Shop Road Ready Products
right_top_byCategorybutton_text=By Category
right_top_TopBrandsbutton_text=Top Brands
right_top_FeaturedItemsbutton_text=Featured Items
