browserName=chrome
url=https://staging.roadreadywheels.com/
splashPassword=roadready
userName=ruby.sharma@w3villa.com
password=1111111111
amazonemail=harshita+sandbox@roadreadywheels.com
amazonpassword=testSandbox
paypalEmailId=sb-jgwdt26214324@personal.example.com
paypaluserpassword=3lAq23<!
#reportEmail=roadready77@gmail.com
#reportKey=xzny szav neza kzsi
reportTo=rishabh.gangwar@w3villa.com

reportEmail=roadreadywheels3@gmail.com
reportKey=oksl rboc vgeo fead

#reportTo=eric.morel@roadreadywheels.com
#reportCC=rrw_website@roadreadywheels.com
#reportBCC1=kundan.kumar@w3villa.com
reportBCC=ruby.sharma@w3villa.com
#reportCC=rrw_website@roadreadywheels.com
#reportBCC1=eric.morel@roadreadywheels.com
#reportBCC2=rrw_website@roadreadywheels.com
reportCC=ruby.sharma@w3villa.com

#reportBCC2=ruby.sharma@w3villa.com
base_url_staging=https://staging.roadreadywheels.com/
search_endpoint=/products/autocomplete
post_product_endpoint=/api/products
gridEnabled=true

gridUrl=http://selenium:4444/wd/hub
api_key_name=X-Spree-Token
api_key=92dc8900cd49cbb75a47f1d116a0022f68abe21bcbd6f9e7
